### ISSUE TITLE
TASKRSRC schema can't handle floats for `target_lag_drtn_hr_cnt`

### ISSUE THREAD

**Issue by michaelrussell4** [jjCode01/xerparser#9]
I tried loading an XER where the TASKRSRC table had a float value for the `target_lag_drtn_hr_cnt` field in one of the rows and it threw an error:

![image](https://github.com/user-attachments/assets/3046d1b3-586b-4bdc-9c47-4db3b0ec4d9c)

I'm no P6 expert, but I don't see any reason this field has to be an int. Can we change it to a float? [ref](https://docs.oracle.com/cd/F37128_01/English/Mapping_and_Schema/xer_import_export_data_map_project/helpmain.htm?toc.htm?97906.htm)

**Comment by jjCode01** [comment]
PR approved and merged.
